### PR TITLE
fix #60 alerts for different teams ending up in the same channel

### LINKED ISSUE #60: alerts for different teams all ending up in the same channel
I'm testing the multiple teams feature, sending mock alerts to mattermost using curl like so:
```
$ curl -i -X POST 'https://mattermost.my.domain/plugins/alertmanager/api/webhook?token=LONG-TEAM-TOKEN' -d '{
  "version": "4",
  "status": "firing",
  "groupKey": "testing",
  "truncatedAlerts": 0,
  "alerts": [
    {
      "annotations": {
          "name": "TestAlert to itds team?"
      },
      "labels": {
          "alertname": "testalert1",
          "instance": "testinstance1",
          "source": "jenkins"
      }
    }
  ]
}'
```

I have created three teams with different names but identical channel names (all use the town-square channel). When I send the above alert using the different tokens, all alerts end up in the channel of the third team! (Note the different AlertManagerPluginId on the different alert messages):
multiple-teams

However, I find the plugin works well if I use the same team and different channels, or several teams and a differently named channel on each. So somewhere in the "multiple teams" feature uses just the channel as a key, whereas different alertmanagers should really be keyed by both team and channel, no?

### PR DESCRIPTION
**Pull request by maxgorovenko**
It would be great if someone could test it too

Fixes: https://github.com/cpanato/mattermost-plugin-alertmanager/issues/60

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by cpanato — APPROVED** [review]
lgtm

**Comment by cpanato** [comment]
@maxgorovenko can you rebase can fix the conflicts?

thanks for this pr

**Comment by hanzei** [comment]
@cpanato This PR is ready for merging

**Pull request merged**
