### PR TITLE
#12 working with multiple teams

### PR DESCRIPTION
**Pull request by maxgorovenko**

### CODE REVIEW

**Comment by maxgorovenko** [comment]
I should explain how it works. First of all we have made a repeatable block in system console plugin settings. To achieve this behavior we had to add webapp module to this plugin.
image

All /commands do everything in loop for each Alert Manager configuration and send replies to configured channels. Except one command expire_silence:
```
/alertmanager expire_silence <ALERT_MANAGER_PLUGIN_ID> <SILENCE_ID> - to expire the specified silence
```
We added one more parameter <ALERT_MANAGER_PLUGIN_ID> to identify the Alert Manager instance, which should receive expire silence request.

All webhook requests get identified by token so there were no difficulties.

**Review by cpanato — COMMENTED** [review]
thanks so much for this huge improvement
i will run a few manual smoke tests and lets get this merged!

**Comment by maxgorovenko** [comment]
@cpanato fixed golangci-lint issues, check please

**Comment by cpanato** [comment]
@maxgorovenko one quick question: for existing users when they upgrade to the new version they will lose the current configuration?

**Comment by maxgorovenko** [comment]
@cpanato yes, existing users will see empty configuration. If it is necessary I can try to implement some kind of migrating at config loading stage

**Comment by cpanato** [comment]
> @cpanato yes, existing users will see empty configuration. If it is necessary I can try to implement some kind of migrating at config loading stage

if that is easy i would say go for it, otherwise we add a breaking change in the release notes.

**Comment by maxgorovenko** [comment]
> if that is easy i would say go for it, otherwise we add a breaking change in the release notes.

Did some research and has concluded that there is no good config migration mechanic and all I can do is to write a code for backward compatibility. But any way someday you will have to add a breaking change and remove that code for backward compatibility. So, now is better choice.

**Comment by cpanato** [comment]
thank you!

**Review by cpanato — APPROVED** [review]

**Pull request merged**
