### PR TITLE
Change alert layout to be more compact

### PR DESCRIPTION
**Pull request by fschlich**
use just two fields as columns and markdown-formatted content, instead
of one field per annotation / label

provide links to alert generator (prometheus) and alertmanager

improve formatting of start/end times (absolute and relative), ommit
bogus end time on firing alerts

DeepinBildschirmfoto_Bereich auswählen_20211124213316

### CODE REVIEW

**Comment by cpanato** [comment]
thanks!

**Comment by fschlich** [comment]
Thanks for accepting my contribution! I noticed your "update version for release" commit, however you haven't pushed a tag, so there's no release available for download at https://github.com/cpanato/mattermost-plugin-alertmanager/releases ?

**Comment by cpanato** [comment]
@fschlich will do soon
thanks for the patch!

**Comment by cpanato** [comment]
@fschlich release here https://github.com/cpanato/mattermost-plugin-alertmanager/releases/tag/v0.2.0

**Pull request merged**
